version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=master
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
 